ARG BASE_IMAGE=ubuntu:22.04
FROM $BASE_IMAGE

# Add repositories and update
RUN add-apt-repository universe -y && \
    apt-get update && \
    apt-get install -y apt-utils software-properties-common wget

# Install tmux, tmuxinator, iputils-ping, python3-tk, and ROS/Gazebo dependencies
RUN apt-get install -y \
    tmux tmuxinator iputils-ping \
    python3-tk \
    python3-rosdep python3-pip python3-colcon-common-extensions \
    python3-colcon-mixin ros-dev-tools \
    python3-flake8 python3-flake8-polyfill python3-flake8-docstrings \
    cppcheck lcov \
    libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
    python3-wstool \
    ros-humble-mocap4r2-msgs ros-humble-mocap4r2-control \
    ros-humble-ros-gz-sim ros-humble-ros-gz-bridge \
    python3-jinja2 python3-pydantic \
    ros-humble-ament-cmake-clang-format ros-humble-geographic-msgs \
    libgeographic-dev \
    ros-humble-teleop-twist-joy \
    libpcl-dev ros-humble-pcl-conversions ros-humble-pcl-ros \
    libapr1-dev libaprutil1-dev \
    libgoogle-glog-dev libeigen3-dev libyaml-cpp-dev \
    ros-$ROS_DISTRO-sophus && rm -rf /var/lib/apt/lists/*

# Install pip packages
RUN pip3 install --upgrade pip && \
    pip3 install \
        kconfiglib jinja2 empy jsonschema pyros-genmsg packaging toml numpy future \
        freesimplegui pymap3d \
        pylint flake8==4.0.1 pycodestyle==2.8 cmakelint cpplint \
        colcon-lcov-result seaborn

# Add colcon mixin and clean up
RUN colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml && \
    colcon mixin update default && \
    rm -rf log

# Add Gazebo repository and update
RUN wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null && \
    apt-get update

# Add GTSAM repository and install
RUN add-apt-repository ppa:borglab/gtsam-release-4.2 -y && \
    apt-get update && \
    apt-get install -y libgtsam-dev libgtsam-unstable-dev

# Upgrade numpy (again, if needed)
RUN pip3 install -U numpy